pipeline:

  simple:
    image: plugins/deb
    description: This is a simple package example only using auto_path for everything
    package: simple-example
    version: 0.0.1
    maintainer: Thomas Frössman<thomasf@jossystem.se>
    homepage: https://example.com
    architecture: all
    auto_path: contrib/debian/deb-pkg/

  no_auto:
    description: Same as the simple example without auto_path
    image: plugins/deb
    package: no-auto-example
    version: 0.0.2
    maintainer: Thomas Frössman<thomasf@jossystem.se>
    architecture: all
    postrm: contrib/debian/deb-pkg/postrm
    files:
      contrib/debian/deb-pkg/etc/testdata.ini: etc/testdata.ini

  files-example:
    description: An example package which uses files to specify adding additional files and control scripts from outside of the auto_path.
    image: plugins/deb
    package: files-example
    version: 1.0.0
    maintainer: Thomas Frössman<thomasf@jossystem.se>
    architecture: all
    auto_path: contrib/debian/deb-pkg/
    postinst: contrib/debian/postinst
    files:
      dirA/somefile: usr/share/my-package-somefile
      .drone.yml: usr/share/my-package-drone.yml

  dependencies-example:
    description: An example package which uses files to specify adding additional files and control scripts from outside of the auto_path.
    image: plugins/deb
    package: deps-example
    version: 1.0.0
    maintainer: Thomas Frössman<thomasf@jossystem.se>
    architecture: all
    auto_path: contrib/debian/deb-pkg/
    depends:
      - python (>= 3.5)
      - go (>= 1.8)
    breaks:
      - simple-example
    replaces:
      - files-example
